// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfR8X1glTa9E32rPxY3xh3G-sbosavRcI',
    appId: '1:378463742818:web:d02933db0df4ac49399a3b',
    messagingSenderId: '378463742818',
    projectId: 'vulpifit',
    authDomain: 'vulpifit.firebaseapp.com',
    storageBucket: 'vulpifit.firebasestorage.app',
    measurementId: 'G-WKTFREP0DN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDOp43K1kQKQHeh44F8YvzXOYJ_PsER0Y',
    appId: '1:378463742818:android:9e3ece06c6957b50399a3b',
    messagingSenderId: '378463742818',
    projectId: 'vulpifit',
    storageBucket: 'vulpifit.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAltQfgRAbAzi63534Y8w84EwweZjsNWxA',
    appId: '1:378463742818:ios:10d3c1b41faa9904399a3b',
    messagingSenderId: '378463742818',
    projectId: 'vulpifit',
    storageBucket: 'vulpifit.firebasestorage.app',
    iosBundleId: 'com.example.VulpiFit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAltQfgRAbAzi63534Y8w84EwweZjsNWxA',
    appId: '1:378463742818:ios:10d3c1b41faa9904399a3b',
    messagingSenderId: '378463742818',
    projectId: 'vulpifit',
    storageBucket: 'vulpifit.firebasestorage.app',
    iosBundleId: 'com.example.VulpiFit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfR8X1glTa9E32rPxY3xh3G-sbosavRcI',
    appId: '1:378463742818:web:dea06b6452c02df1399a3b',
    messagingSenderId: '378463742818',
    projectId: 'vulpifit',
    authDomain: 'vulpifit.firebaseapp.com',
    storageBucket: 'vulpifit.firebasestorage.app',
    measurementId: 'G-4X8NZWQY2L',
  );
}
